#argumentos para o dataset
nclass: 2
crop_size: 321
data_root: data/subpipe  #arrumar isso]

#argumentos para o treino
epochs: 80
batch_size: 2 #padrão deles para 4 gpus
lr: 0.002
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

#argumentos para o modelo
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
